import mongoose from "mongoose";
import dotenv from "dotenv";
import Trail from "../models/Trail.js";

dotenv.config();

const trails = [
    {
        name: "Kalinchowk Bhagwati Trek",
        location: "Dolakha",
        difficulty: "Moderate",
        distance: "12 km one way",
        duration: "5–6 hours",
        description: "Located in Dolakha District, this trek starts from Charikot (~1,550m), about a 5-6 hour drive from Kathmandu (150km). From Charikot, trekkers either hike (12km) or use the cable car section from Kuri Village (3,200m) to reach the Kalinchowk Bhagwati shrine at (3,842m) The trail passes through Sherpa and Tamang villages, dense rhododendron forests, and open ridges.Trekkers can enjoy panoramic Himalayan views, including Mt.Gaurishankar, Jugal range, and Everest in clear weather.The trek is ideal for 2–3 days; moderate difficulty with steep sections near the top.Best seasons: spring(March–May) and winter(Dec–Feb)",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762567391/OIP_psmovo.webp",
        coordinates: { lat: 27.6719, lng: 86.0243 },
        elevation: "3,842 m ",
        startingPoint: "Charikot",
        bestSeason: "Spring (March–May) & Winter (Dec–Feb)",
        stars: 4,
        reviews: 17,
    },
    {
        name: "Phulchoki Hike",
        location: "Lalitpur",
        difficulty: "Moderate",
        distance: "8 km one way (16 km round trip)",
        duration: "4–6 hours one way",
        description: "A one-day hike starting at Godavari (~1,500 m), just outside Kathmandu. The trail climbs ~1,200 m to the summit at ~2,782 m, covering ~8 km one-way (16 km round-trip). The route winds through lush forests, rhododendron zones, and bird-rich habitats, hosting over 250 species. Hikers get panoramic views of the Kathmandu Valley and distant Himalayan ranges like Langtang and Gaurishankar. The trail is moderate in difficulty and ideal for a day trip. Best done early to enjoy sunrise and avoid descending in late afternoon.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762569882/phulchoki-hill-hiking_fb90oz.webp",
        coordinates: { lat: 27.5819, lng: 85.3913 },
        elevation: "2,285–2,520 m ",
        startingPoint: "Godavari  ",
        bestSeason: "Spring (March–May) & Autumn (Sept–Nov)",
        stars: 5,
        reviews: 27,
    },
    {
        name: "Champadevi Hike",
        location: "Kirtipur, Kathmandu",
        difficulty: "Moderate",
        distance: "7 km one way",
        duration: "3–5 hours one wa",
        description: "This hike starts near Pharping (~1,400 m), about 30–45 minutes from Kathmandu. The summit reaches ~2,285–2,520 m, with a round-trip distance of ~13–15 km. The trail passes through pine and rhododendron forests, local monasteries, and the Champadevi Temple. Hikers are rewarded with panoramic views of Kathmandu Valley and distant Himalayan peaks such as Langtang and Annapurna. Suitable for beginners with moderate fitness. Duration: 4–6 hours. Best visited in spring or autumn for clear views.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762570031/Hikers-starting-their-Champadevi-Hiking-from-Bhanjyang-Dakshinkali_puag3i.jpg",
        coordinates: { lat: 27.6553, lng: 85.2641 },
        elevation: "2,285–2,520 m",
        startingPoint: "Pharping ",
        bestSeason: "Spring & Autumn",
        stars: 5,
        reviews: 24,
    },
    {
        name: "Sundarijal to Chisapani Trek",
        location: "Shivapuri National Park",
        difficulty: "Moderate",
        distance: "14 km one way",
        duration: "5–7 hours one way",
        description: "Located in Shivapuri National Park, this trek begins at Sundarijal (~1,350 m) and ascends to Chisapani (~2,120 m), covering ~14 km one-way. Duration: 5–7 hours depending on pace. The route passes waterfalls, dense forests, and small villages. It offers views of the Shivapuri Hills and Kathmandu Valley. Hikers experience moderate difficulty with steady uphill climbs. This trek is popular for day hikes and overnight camping. Best seasons: spring and autumn. Cultural highlights include local Gurung and Tamang villages along the way.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762570062/stairs-in-hiking-1_qywqts.jpg",
        coordinates: { lat: 27.7955, lng: 85.3975 },
        elevation: "2,120 m",
        startingPoint: "Sundarijal ",
        bestSeason: "Spring & Autumn",
        stars: 4,
        reviews: 16,
    },
    {
        name: "Namobuddha Hike",
        location: "Kavrepalanchok",
        difficulty: "Easy",
        distance: "8 km one way",
        duration: "3-4 hours one way",
        description: "This easy hike starts from Dhulikhel (~1,550 m), about 30–40 km east of Kathmandu. The trail stretches ~8 km one-way, taking 3–4 hours to reach Namobuddha (~1,750 m). The route passes through terraced fields, small villages, and pine forests. Along the way, hikers can see traditional Newari and Tamang settlements and enjoy views of the Kathmandu Valley and distant Himalayan peaks like Langtang and Gaurishankar. Namobuddha is a sacred Buddhist monastery, making this hike culturally enriching as well. Ideal for a half-day or full-day hike; very beginner-friendly. Best seasons: spring and autumn.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762570086/ec_ied1zd.jpg",
        coordinates: { lat: 27.6150, lng: 85.5934 },
        elevation: "1,750 m",
        startingPoint: "Dhulikhel ",
        bestSeason: "Spring & Autumn",
        stars: 4,
        reviews: 17,
    },
    {
        name: "Khopra Ridge Trek",
        location: "Annapurna Region",
        difficulty: "Hard",
        distance: "45 km one way",
        duration: "5-7 days",
        description: "Located in the Annapurna region, this trek begins at Nayapul (~1,070 m) and continues via Ghorepani (~2,860 m) to Khopra Ridge (~3,660 m). Total distance is ~45 km, taking 5–7 days. The trail offers panoramic views of Annapurna, Dhaulagiri, and Machhapuchhre. Trekkers pass through rhododendron forests, remote villages, and suspension bridges. The trek is less crowded than the popular ABC trek, giving a peaceful alpine experience. Moderate to hard difficulty due to steep ascents and high altitude. Best seasons: March–May and September–November.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762573970/BlogspotImageUrl-66097-Bikat-Adventures_azajjt.jpg",
        coordinates: { lat: 28.4735, lng: 83.7431 },
        elevation: "3,660 m",
        startingPoint: "Nayapul",
        bestSeason: "Spring (March–May) & Autumn (Sept–Nov)",
        stars: 3,
        reviews: 10,
    },
    {
        name: "Makalu Base Camp Trek",
        location: "Makalu-Barun National Park",
        difficulty: "Hard",
        distance: "75 km one way",
        duration: "14-18 days",
        description: "A challenging trek in Makalu-Barun National Park, starting from Tumlingtar (~1,300 m). The trek covers ~75 km to Makalu Base Camp (~4,800 m) over 14–18 days. The route passes through pristine forests, remote villages, and high-altitude landscapes, with breathtaking views of Makalu (8,481 m), the 5th highest peak in the world. Trekkers experience challenging ascents, glacial moraines, and suspension bridges. Hard difficulty, suitable for experienced hikers. Best seasons: spring (April–May) and autumn (October–November).",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574009/makalu-base-camp_tomja5.jpg",
        coordinates: { lat: 27.8867, lng: 87.0870 },
        elevation: "4,800 m",
        startingPoint: "Tumlingtar ",
        bestSeason: "Spring (April–May) & Autumn (Oct–Nov)",
        stars: 4,
        reviews: 15,
    },
    {
        name: "Helambu Trek",
        location: "Sindhupalchowk",
        difficulty: "Moderate",
        distance: "35 km one way",
        duration: "4-6 days",
        description: "This moderate trek begins at Sundarijal (~1,350 m) and stretches to Melamchi Bazaar (~2,100 m) and beyond, covering ~35 km over 4–6 days. Helambu is famous for rhododendron forests, Sherpa villages, and traditional Tamang culture. Trekkers pass through terraced fields, monasteries, and alpine forests, enjoying views of Langtang Himal and surrounding valleys. Moderate difficulty with gradual ascents. Suitable for hikers seeking cultural immersion combined with scenic trekking. Best seasons: spring and autumn.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574258/helambu-trek_jwokow.webp",
        coordinates: { lat: 28.1280, lng: 85.5304 },
        elevation: "2,100 m",
        startingPoint: "Sundarijal ",
        bestSeason: "Spring & Autumn",
        stars: 4,
        reviews: 18,
    },
    {
        name: "Upper Mustang Trek",
        location: "Mustang",
        difficulty: "Hard",
        distance: "80 km one way",
        duration: "10-14 days",
        description: "Located in Mustang District, this trek starts at Jomsom (~2,700 m) and extends to Lo Manthang (~3,840 m), covering ~80 km over 10–14 days. This high-altitude trek passes through arid landscapes, deep canyons, and Tibetan-style villages. Trekkers experience unique Tibetan culture, ancient monasteries, and desert-like scenery. Elevation gains are gradual but challenging, with the trek reaching altitudes above 4,000 m at several points. Moderate to hard difficulty due to remoteness and altitude. Best seasons: spring (March–May) and autumn (September–November). Water and supplies are limited along the trail, so preparation is essential.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574476/why-trek-upper-mustang-nepal.jpg_q6xgsn.webp",
        coordinates: { lat: 29.1781, lng: 83.9702 },
        elevation: "3,840 m",
        startingPoint: "Jomsom",
        bestSeason: "Spring (March–May) & Autumn (Sept–Nov)",
        stars: 5,
        reviews: 25,
    },
    {
        name: "Rara Lake Trek",
        location: "Mugu",
        difficulty: "Moderate",
        distance: "20 km one way",
        duration: "3-5 days",
        description: "Starting from Jumla (~2,350 m), this trek covers ~20 km over 3–5 days to reach Rara Lake (~2,990 m), Nepal’s largest lake. The trail passes through dense forests, remote villages, and alpine meadows. Trekkers enjoy views of snow-capped peaks surrounding the lake and can spot unique flora and fauna endemic to the region. Moderate difficulty; trekking days are relatively short but involve uphill sections. Best seasons: spring (March–May) and autumn (September–November). Accommodation is limited to basic lodges, adding a rustic charm to the trek.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574536/image_vbmroq.jpg",
        coordinates: { lat: 29.5237, lng: 82.0885 },
        elevation: "2,990 m",
        startingPoint: "Jumla ",
        bestSeason: "Spring (March–May) & Autumn (Sept–Nov)",
        stars: 4,
        reviews: 17,
    },
    {
        name: "Tsho Rolpa Lake Trek",
        location: "Rolwaling Valley",
        difficulty: "Hard",
        distance: "32 km one way",
        duration: "5-7 days",
        description: "This high-altitude trek starts at Simigaun (~2,600 m) in Rolwaling Valley and leads to Tsho Rolpa Lake (~4,580 m), covering ~32 km over 5–7 days. The trail passes through dense pine and rhododendron forests, traditional Sherpa villages, and glacial moraines. Trekkers witness stunning alpine landscapes, including views of Gauri Shankar and Melungtse peaks. Hard difficulty due to high altitude and steep terrain. Best seasons: spring (April–May) and autumn (September–October). Preparations for cold weather and limited supplies are essential.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574571/bdeing-village_wxgdwe.png",
        coordinates: { lat: 27.8694, lng: 86.4062 },
        elevation: "4,580 m",
        startingPoint: "Simigaun ",
        bestSeason: "Spring (April–May) & Autumn (Sept–Oct)",
        stars: 4,
        reviews: 16,

    },
    {
        name: "Ghandruk Village Trek",
        location: "Kaski",
        difficulty: "Easy",
        distance: "6 km one way",
        duration: "2-3 hours one way",
        description: "Starting at Nayapul (~1,070 m) in the Annapurna region, this easy trek covers ~6 km one-way, taking 2–3 hours to reach Ghandruk Village (~2,010 m). The route passes through terraced fields, pine and rhododendron forests, and small Gurung settlements. Trekkers enjoy panoramic views of Annapurna and Machhapuchhre. This is a culturally rich trek, allowing hikers to experience traditional Gurung lifestyle. Beginner-friendly with gradual ascents, suitable for half-day or full-day hikes. Best seasons: spring and autumn.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574627/ghandruk-village_lrvqaq.jpg",
        coordinates: { lat: 28.3769, lng: 83.8021 },
        elevation: "2,010 m",
        startingPoint: "Nayapul ",
        bestSeason: "Spring & Autumn",
        stars: 5,
        reviews: 24,
    },
    {
        name: "Khumai Danda Trek",
        location: "Kaski",
        difficulty: "Moderate",
        distance: "18 km one way",
        duration: "2-3 days",
        description: "This moderate trek begins near Dhampus (~1,650 m) in Kaski District and stretches to Khumai Danda (~2,600 m), covering ~18 km over 2–3 days. The trail passes through terraced fields, rhododendron forests, and small Gurung villages. Trekkers enjoy close-up views of Mt. Machhapuchhre and the Annapurna range. The route provides cultural experiences with local village life and traditional homestays. Moderate difficulty due to steady uphill climbs. Best seasons: spring and autumn. Ideal for hikers who want scenic views combined with cultural immersion.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574680/maxresdefault_shten6.jpg",
        coordinates: { lat: 28.3706, lng: 83.9516 },
        elevation: "2,600 m",
        startingPoint: "Dhampus ",
        bestSeason: "Spring & Autumn",
        stars: 4,
        reviews: 16,
    },
    {
        name: "Shey Phoksundo Lake Trek",
        location: "Dolpa",
        difficulty: "Hard",
        distance: "34 km one way",
        duration: "5-7 days",
        description: "Starting at Dunai (~2,050 m) in Dolpa, this high-altitude trek covers ~34 km over 5–7 days to reach Shey Phoksundo Lake (~3,611 m), located inside Shey Phoksundo National Park. The trail passes through alpine forests, high desert landscapes, and small Tibetan-style villages. Trekkers are rewarded with views of turquoise Phoksundo Lake, snow-capped peaks, and Buddhist monasteries. Hard difficulty due to altitude, long distances, and remote terrain. Best seasons: spring (April–May) and autumn (September–October). Essential to carry supplies as services are limited along the route.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762574766/big-c7841c01b98201b8f16522f34e03c3d4_gavqzq.jpg",
        coordinates: { lat: 29.1851, lng: 82.9333 },
        elevation: "3,611 m",
        startingPoint: "Dunai ",
        bestSeason: "Spring (April–May) & Autumn (Sept–Oct)",
        stars: 3,
        reviews: 8,
    },
    {
        name: "Ghorepani Poon Hill Trek",
        location: "Annapurna Region",
        difficulty: "Moderate",
        distance: "32 km one way",
        duration: "4-5 days",
        description: "This popular trek starts at Nayapul (~1,070 m) and goes through Tikhedhunga and Ghorepani (~2,850 m), covering ~32 km over 4–5 days. The trail passes through rhododendron forests, local Gurung villages, and terraced farmlands. The highlight is Poon Hill (~3,210 m), offering a panoramic sunrise view of Annapurna and Dhaulagiri ranges. Moderate difficulty with gradual ascents and well-marked trails. Best seasons: spring and autumn. Ideal for both beginners and experienced hikers seeking stunning Himalayan vistas.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762575841/Ghorepani-pool-hill-trek_snbs7t.jpg",
        coordinates: { lat: 28.4006, lng: 83.9142 },
        elevation: "3,210 m",
        startingPoint: "Nayapul ",
        bestSeason: "Spring & Autumn",
        stars: 3,
        reviews: 7,
    },
    {
        name: "Langtang Valley Trek",
        location: "Langtang National Park",
        difficulty: "Moderate",
        distance: "40 km one way",
        duration: "5-7 days",
        description: "Starting at Syabrubesi (~1,500 m), this trek covers ~40 km over 5–7 days, reaching Kyanjin Gompa (~3,870 m) in Langtang National Park. The trail passes through subtropical forests, rhododendron groves, traditional Tamang villages, and offers views of Langtang Lirung and other Himalayan peaks.Trekkers experience local culture, monasteries, and glacial streams.Moderate difficulty; altitude gain is steady but manageable.Best seasons: spring and autumn.Trekking here offers a mix of natural beauty, culture, and Himalayan adventure.",
        image: "https://res.cloudinary.com/dorwxf5yq/image/upload/v1762575898/langtang-trek-7-days-I_im6ts4.jpg",
        coordinates: { lat: 28.2133, lng: 85.5333 },
        elevation: "3,870 m",
        startingPoint: "Syabrubesi ",
        bestSeason: "Spring & Autumn",
        stars: 4,
        reviews: 17,
    }
];

const seedTrails = async () => {
    await mongoose.connect(process.env.MONGO_URL_TRAILS);
    await Trail.deleteMany({}); // Clear old data
    await Trail.insertMany(trails); // Add new data
    console.log("Database seeded with trails!");
    mongoose.disconnect();
};

seedTrails();
